services:
  python-benchmark:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: pl-ingestion-python:latest
    working_dir: /app
    volumes:
      - ./data:/app/data
  go-benchmark:
    build:
      context: ./go
      dockerfile: Dockerfile
    image: pl-ingestion-go:latest
    working_dir: /app
    volumes:
      - ./data:/app/data
  rust-benchmark:
    build:
      context: ./rust
      dockerfile: Dockerfile
    image: pl-ingestion-rust:latest
    working_dir: /app
    volumes:
      - ./data:/app/data
  java-benchmark:
    build:
      context: ./java
      dockerfile: Dockerfile
    image: pl-ingestion-java:latest
    working_dir: /app
    volumes:
      - ./data:/app/data
