services:
  python-benchmark:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: pl-ingestion-python:latest
    working_dir: /app
    volumes:
      - ./data:/app/data
  go-benchmark:
    build:
      context: ./go
      dockerfile: Dockerfile
    image: pl-ingestion-go:latest
    working_dir: /app
    volumes:
      - ./data:/app/data
